/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package server;

import io.grpc.Server;
import io.grpc.ServerBuilder;
import io.grpc.examples.GreeterGrpc;

import java.io.IOException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) throws IOException, InterruptedException {

        System.out.println(new App().getGreeting());
        Server server = ServerBuilder.forPort(3000)
                .addService(new GreeterServerImpl())
                .build();

        server.start();

        server.awaitTermination();
    }
}

