/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package client;

import io.grpc.Channel;
import io.grpc.ManagedChannel;
import io.grpc.ManagedChannelBuilder;
import io.grpc.StatusRuntimeException;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        ManagedChannel channel = ManagedChannelBuilder.forTarget(target).usePlaintext().build();

    }
}

